### PR TITLE
Added Footer 

### PR DESCRIPTION
**Pull request by SachinMittal1766**
I have added footer in all pages. @ghulamyazdani pls check it once.

### CODE REVIEW

**Comment by SachinMittal1766** [comment]
@ghulamyazdani I think now all conflicts in files are resolved. Pls check it once.

**Comment by ghulamyazdani** [comment]
Still same issue

**Comment by SachinMittal1766** [comment]
When I checked by clicking on the "View development" option, everything seemed correct. I am not getting where the issue is arising.

**Comment by akshatnema** [comment]
Hey @SachinMittal1766, Kindly look over this issue on the Quiz page. Footer is placed a bit above its actual place.

## Preview of Error
Screenshot 2021-12-11 200345

**Comment by SachinMittal1766** [comment]
@ghulamyazdani I have made the changes. Hopefully, now the problem will be sorted.

**Comment by akshatnema** [comment]
LGTM @SachinMittal1766 🥳. Merging this PR.

**Pull request merged**
