### PR TITLE
Added FAQ Section

### PR DESCRIPTION
**Pull request by snahashisk**
Fixed Issue #92 
Please review it @ghulamyazdani

### CODE REVIEW

**Comment by ghulamyazdani** [comment]
image
@snahashisk The mobile view for this section is not responsive can you take care of that?

**Comment by snahashisk** [comment]
yeah sure

**Comment by snahashisk** [comment]
Please review it @ghulamyazdani

**Review by ghulamyazdani — APPROVED** [review]
LGTM 🥳

**Pull request merged**
