### PR TITLE
Info page

### LINKED ISSUE #51: Video section looks odd
The Video section on the info page looks a  bit odd.

Screenshot (1199)

Hey, I would like to fix this issue. Can you please assign this to me?

### PR DESCRIPTION
**Pull request by arpita221b**
fixes #51 
Screenshot (1205)

### CODE REVIEW

**Comment by akshatnema** [comment]
Hey @arpita221b, Good work in improving the info page. If possible, kindly look over the same issue in mobile view as well, so as to improve responsiveness on that page. There is an extra unnecessary space between links and the youtube player (as shown in preview). Try to remove that space as well in mobile view.

## Preview of Error
image

**Comment by ghulamyazdani** [comment]
> Hey @arpita221b, Good work in improving the info page. If possible, kindly look over the same issue in mobile view as well, so as to improve responsiveness on that page. There is an extra unnecessary space between links and the youtube player (as shown in preview). Try to remove that space as well in mobile view.
> 
> ## Preview of Error
> image

yeah @arpita221b if you could do that pls let us know!

**Comment by arpita221b** [comment]
Hey, I'll try solving this issue!
And I will tell you if am not able to.

**Comment by arpita221b** [comment]
It's done!

**Review by akshatnema — APPROVED** [review]

**Comment by akshatnema** [comment]
LGTM @arpita221b 🥳. You have made good changes for adding responsiveness to the website. Merging this PR now.

**Pull request merged**
