### PR TITLE
modifications in issue 19 Adding audio visualiser-second pull request

### PR DESCRIPTION
**Pull request by MayankRaje**
I have done some modifications in HTML and CSS part which looks more attractive to the user

https://drive.google.com/file/d/1afTml-fiv_R7-kpwjUvaULVAto1DypTp/view?usp=drivesdk
https://drive.google.com/file/d/1abfPxS5wtxtpWNExscSGuTgrabc1WngF/view?usp=drivesdk
https://drive.google.com/file/d/1aejhZ5Cb2xQm1G4pJxogaKa2JG7ajqq-/view?usp=drivesdk

### CODE REVIEW

**Comment by ghulamyazdani** [comment]
Can you add a button or something which will take back users to the homepage?

**Comment by MayankRaje** [comment]
> Can you add a button or something which will take back users to the homepage?

ok sir

**Comment by MayankRaje** [comment]
Sir i have attached a home page button ton it and created a new pull request 
Name: modifications in issue 19 Adding AUDIO_VISUALIZER and HOMEPAGE buttton #81
please have a look on it

**Comment by MayankRaje** [comment]
Sir i have attached a home page button to AUDIO_VISUALIZER and created a new pull request
Name: modifications in issue 19 Adding AUDIO_VISUALIZER and HOMEPAGE buttton #81
please have a look on it

**Pull request closed without merging**
