### PR TITLE
fix: navbar-scroll-feature-removed

### LINKED ISSUE #40: fix: Navbar-scroll-feature-remove
Hello,
The feature where the navigation bar disappears on the scroll is not useful.
Reasons:
- The navbar stays on the top and doesn't affect other content on the page so no point in removing it
- The vanished navbar affects the user  negatively while they are exploring the info page

image

As you can see here that the navbar has disappeared just by scrolling a little bit.
This would decrease user experience.

I would like to remove this feature.

Please assign this issue to me. 😊

### PR DESCRIPTION
**Pull request by Keshraf**
Removing the feature where the Navigation Bar disappears on scroll.

fix #40

### CODE REVIEW

**Review by akshatnema — CHANGES_REQUESTED** [review]
The Font styling in the info webpage is changing in the preview. Kindly look over this issue on the info page.

Previous:
image

After changes:
image

**Comment by Keshraf** [comment]
Hello @akshatnema,
A contributor had made a PR recently where he had made changes to the font. I think that the PR is not update.
How can I update it to reflect the new changes?

**Comment by Keshraf** [comment]
@akshatnema the issue is fixed now. Please check

**Comment by ghulamyazdani** [comment]
@akshatnema merging this PR won't affect the current font of  it will remain the same!

**Comment by akshatnema** [comment]
Yep, LGTM @Keshraf. Merging this PR.

**Pull request merged**
