### PR TITLE
Modified GetHelp buttons 

### PR DESCRIPTION
**Pull request by SachinMittal1766**
@ghulamyazdani I have modified the CSS of GetHelp sections buttons. Pls check it.

### CODE REVIEW

**Comment by ghulamyazdani** [comment]
I think the previous version was better.

**Comment by SachinMittal1766** [comment]
I think hover effect looks good. I will change color of button to previous version. @ghulamyazdani Does it sounds good ?

**Comment by SachinMittal1766** [comment]
@ghulamyazdani committed some modifications.

**Comment by SachinMittal1766** [comment]
@ghulamyazdani Any updates ?

**Review by ghulamyazdani — APPROVED** [review]
LGTM 🥳

**Pull request merged**
